---
# This file configures https://pre-commit.com/
#
# Based on pre-commit hooks in
#   https://github.com/pre-commit/pre-commit-hooks
#   https://github.com/cmake-lint/cmake-lint

repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        name: CMake Format
        entry: cmake-format --line-width 100
      - id: cmake-lint
        name: CMake Lint 1
        entry: cmake-lint --line-width 100
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.2
    hooks:
      - id: cmakelint
        name: CMake Lint 2
        args:
          - "--linelength=100"
          - "--filter=-whitespace/indent"
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: mixed-line-ending
